language: python
python: 3.5.1

env:
  global:
    - TRAVIS_NODE_VERSION=5.5.0

dist: trusty
sudo: false

addons:
  postgresql: "9.4"

services:
  - postgresql

cache:
  directories:
    - ~/.cache/pip
    - node_modules/

install:
  - 'rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION'
  - pip install -U pip setuptools wheel codecov
  - pip install -r requirements/docs.txt -r requirements/lint.txt -r requirements/main.txt -r requirements/tests.txt
  - npm install

script:
  - node -v
  - npm -v
  - gulp dist
  - bin/tests --dbfixtures-config tests/dbfixtures.travis.conf

matrix:
  include:
    - script: make lint BINDIR="$(dirname $(which python))"
    - script: make docs BINDIR="$(dirname $(which python))"

after_success: codecov

notifications:
  irc:
    channels:
      - "irc.freenode.org#pypa-dev"
    use_notice: true
    skip_join: true
